name: akos_app
description: Application AKOS pour trouver des partenaires sportifs
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Image et HTTP
  image: ^4.5.3 
  http: ^0.13.5
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1

  # Supabase
  supabase_flutter: ^1.10.25

  # Navigation
  go_router: ^13.2.5

  # Autres dépendances
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  uuid: ^4.0.0
  timeago: ^3.5.0
  url_launcher: ^6.3.1

  # Optionnelles
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#3B82F6"
  image: "assets/images/splash.png"
  android_12:
    color: "#3B82F6"
    image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600